language: R
cache: packages
sudo: false
warnings_are_errors: true

r:
- oldrel
- release
- devel

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libxml2-dev # for XML, a dependency of quanteda

r_packages:
  - covr
  - data.table # so data.table tests will get checked

after_success:
  - Rscript -e 'covr::codecov(coverage = covr::package_coverage(line_exclusions = list("R/compat_lazyeval.R")))'
